import Item from "./Item";

const products = [
    new Item(
        "Office Lite",
        "Avtech",
        "PC",
        2_660_000,
        50,
        2018,
        "black",
        false,
        "assets/image/office-pc.png",
        false
    ),
    new Item(
        "Office Standard",
        "Avtech",
        "PC",
        2_755_000,
        40,
        2019,
        "blue",
        false,
        "assets/image/blue-pc.png",
        true
    ),
    new Item(
        "Office Pro",
        "Avtech",
        "PC",
        3_780_000,
        20,
        2020,
        "black",
        false,
        "assets/image/cyber-pc.png",
        false
    ),
    new Item(
        "Office Lite+",
        "Avtech",
        "PC",
        3_110_000,
        25,
        2018,
        "black",
        false,
        "assets/image/gamer-elite-pc.png",
        false
    ),
    new Item(
        "Office Pro+",
        "Avtech",
        "PC",
        4_045_000,
        50,
        2018,
        "red",
        false,
        "assets/image/red-pc.png",
        true
    ),
    new Item(
        "Office Elite+",
        "Avtech",
        "PC",
        5_645_000,
        50,
        2018,
        "yellow",
        false,
        "assets/image/yellow-pc.png",
        false
    ),
    new Item(
        "Champion PC",
        "Avtech",
        "PC",
        54_360_000,
        5,
        2022,
        "black",
        false,
        "assets/image/champion-pc.png",
        false
    ),
    new Item(
        "Ultra Extreme PC",
        "Avtech",
        "PC",
        86_900_000,
        2,
        2022,
        "white",
        false,
        "assets/image/ultra-white-pc.png",
        false
    ),
    new Item(
        "Game Rock PC",
        "Avtech",
        "PC",
        8_875_000,
        25,
        2022,
        "white",
        false,
        "assets/image/rock-pc.png",
        true
    ),
    new Item(
        "OMG Gaming PC",
        "Avtech",
        "PC",
        8_260_000,
        16,
        2022,
        "black",
        false,
        "assets/image/omg-pc.png",
        false
    ),
    new Item(
        "Acer A3",
        "Acer",
        "Laptop",
        5_852_000,
        30,
        2020,
        "blue",
        false,
        "assets/image/acer-a3.png",
        false
    ),
    new Item(
        "Lenovo V15",
        "Lenovo",
        "Laptop",
        6_446_000,
        45,
        2018,
        "black",
        false,
        "assets/image/lenovo-v15.png",
        false
    ),
    new Item(
        "HP Pavilion",
        "HP",
        "Laptop",
        7_040_000,
        18,
        2021,
        "white",
        false,
        "assets/image/hp-pavilion.png",
        true
    ),
    new Item(
        "Asus Zenbook",
        "Asus",
        "Laptop",
        30_250_000,
        4,
        2022,
        "black",
        false,
        "assets/image/asus-zenbook.png",
        false
    ),
    new Item(
        "Lenovo ThinkPad",
        "Lenovo",
        "Laptop",
        21_857_000,
        5,
        2022,
        "black",
        false,
        "assets/image/lenovo-thinkpad.png",
        true
    ),
    new Item(
        "IdealCentre",
        "Lenovo",
        "Monoblock",
        7_450_000,
        11,
        2022,
        "black",
        false,
        "assets/image/monoblock-idealcenter.png",
        false
    ),
    new Item(
        "Acer Aspire",
        "Acer",
        "Monoblock",
        9_900_000,
        25,
        2022,
        "white",
        false,
        "assets/image/acer-aspire.png",
        true
    ),
    new Item(
        "Acer-38",
        "Acer",
        "Monitor",
        13_490_000,
        17,
        2020,
        "black",
        false,
        "assets/image/acer-38.png",
        false
    ),
    new Item(
        "Lenovo-43,4",
        "Lenovo",
        "Monitor",
        14_120_000,
        26,
        2021,
        "black",
        false,
        "assets/image/lenovo-43.png",
        false
    ),
    new Item(
        "HP-43",
        "HP",
        "Monitor",
        17_980_000,
        34,
        2022,
        "black",
        false,
        "assets/image/hp-43.png",
        true
    ),
    new Item(
        "Acer-24",
        "Acer",
        "Monitor",
        2_190_000,
        57,
        2019,
        "black",
        false,
        "assets/image/acer-24.png",
        false
    )
];

export default products;